export const CLIENTES = [
  {
    idCliente: 1,
    nombre: "Juan Pérez",
    ruc: "20123456789",
    direccion: "Av. Principal 123, Lima",
    telefono: "987654321",
    correo: "juan.perez@example.com",
    documentoDeIdentidad: "45678901",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 2,
    nombre: "María Gómez",
    ruc: "20456789012",
    direccion: "Calle Los Olivos 456, Cusco",
    telefono: "912345678",
    correo: "maria.gomez@example.com",
    documentoDeIdentidad: "78901234",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 3,
    nombre: "Carlos Martínez",
    ruc: "20987654321",
    direccion: "Av. San Martín 789, Arequipa",
    telefono: "963258741",
    correo: "carlos.martinez@example.com",
    documentoDeIdentidad: "12345678",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 4,
    nombre: "Ana Rodríguez",
    ruc: "20123456789",
    direccion: "Calle de la Cultura 123, Trujillo",
    telefono: "987654321",
    correo: "ana.rodriguez@example.com",
    documentoDeIdentidad: "23456789",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 5,
    nombre: "Luis Fernández",
    ruc: "20876543210",
    direccion: "Av. Puno 200, Piura",
    telefono: "987654321",
    correo: "luis.fernandez@example.com",
    documentoDeIdentidad: "34567890",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 6,
    nombre: "Elena Rodríguez",
    ruc: "20234567890",
    direccion: "Calle Los Andes 456, Ica",
    telefono: "916732540",
    correo: "elena.rodriguez@example.com",
    documentoDeIdentidad: "98765432",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 7,
    nombre: "Pedro Sánchez",
    ruc: "20765432109",
    direccion: "Calle Libertad 789, Chiclayo",
    telefono: "936485761",
    correo: "pedro.sanchez@example.com",
    documentoDeIdentidad: "56473829",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 8,
    nombre: "Lucía Torres",
    ruc: "20654321098",
    direccion: "Av. Las Flores 321, Puno",
    telefono: "930284756",
    correo: "lucia.torres@example.com",
    documentoDeIdentidad: "87654321",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 9,
    nombre: "José López",
    ruc: "20398765432",
    direccion: "Calle Los Jazmines 654, Cajamarca",
    telefono: "987654321",
    correo: "jose.lopez@example.com",
    documentoDeIdentidad: "11223344",
    tipoDeDocumento: "DNI",
  },
  {
    idCliente: 10,
    nombre: "Patricia Díaz",
    ruc: "20543210987",
    direccion: "Av. Miraflores 123, Lima",
    telefono: "945872630",
    correo: "patricia.diaz@example.com",
    documentoDeIdentidad: "44332211",
    tipoDeDocumento: "DNI",
  },
];

export const EMPLEADOS = [
  {
    idEmpleado: 1,
    usuario: "juanperez",
    password: "password123",
    nombre: "Juan",
    apellido: "Pérez",
    correo: "juan.perez@example.com",
    telefono: "987654321",
    direccion: "Av. Principal 123, Lima",
    documentoIdentidad: "45678901",
    tipoDocumento: "DNI",
    rol: "jefe",
  },
  {
    idEmpleado: 2,
    usuario: "mariagomez",
    password: "password456",
    nombre: "María",
    apellido: "Gómez",
    correo: "maria.gomez@example.com",
    telefono: "912345678",
    direccion: "Calle Los Olivos 456, Cusco",
    documentoIdentidad: "78901234",
    tipoDocumento: "DNI",
    rol: "tecnico",
  },
  {
    idEmpleado: 3,
    usuario: "carlosmartinez",
    password: "password789",
    nombre: "Carlos",
    apellido: "Martínez",
    correo: "carlos.martinez@example.com",
    telefono: "963258741",
    direccion: "Av. San Martín 789, Arequipa",
    documentoIdentidad: "12345678",
    tipoDocumento: "DNI",
    rol: "supervisor",
  },
  {
    idEmpleado: 4,
    usuario: "anarodriguez",
    password: "password012",
    nombre: "Ana",
    apellido: "Rodríguez",
    correo: "ana.rodriguez@example.com",
    telefono: "987654321",
    direccion: "Calle de la Cultura 123, Trujillo",
    documentoIdentidad: "23456789",
    tipoDocumento: "DNI",
    rol: "tecnico",
  },
  {
    idEmpleado: 5,
    usuario: "luisfernandez",
    password: "password345",
    nombre: "Luis",
    apellido: "Fernández",
    correo: "luis.fernandez@example.com",
    telefono: "987654321",
    direccion: "Av. Puno 200, Piura",
    documentoIdentidad: "34567890",
    tipoDocumento: "DNI",
    rol: "jefe",
  },
  {
    idEmpleado: 6,
    usuario: "elenarodriguez",
    password: "password678",
    nombre: "Elena",
    apellido: "Rodríguez",
    correo: "elena.rodriguez@example.com",
    telefono: "916732540",
    direccion: "Calle Los Andes 456, Ica",
    documentoIdentidad: "98765432",
    tipoDocumento: "DNI",
    rol: "tecnico",
  },
  {
    idEmpleado: 7,
    usuario: "pedrosanchez",
    password: "password901",
    nombre: "Pedro",
    apellido: "Sánchez",
    correo: "pedro.sanchez@example.com",
    telefono: "936485761",
    direccion: "Calle Libertad 789, Chiclayo",
    documentoIdentidad: "56473829",
    tipoDocumento: "DNI",
    rol: "tecnico",
  },
  {
    idEmpleado: 8,
    usuario: "luciatorres",
    password: "password234",
    nombre: "Lucía",
    apellido: "Torres",
    correo: "lucia.torres@example.com",
    telefono: "930284756",
    direccion: "Av. Las Flores 321, Puno",
    documentoIdentidad: "87654321",
    tipoDocumento: "DNI",
    rol: "supervisor",
  },
  {
    idEmpleado: 9,
    usuario: "joselopez",
    password: "password567",
    nombre: "José",
    apellido: "López",
    correo: "jose.lopez@example.com",
    telefono: "987654321",
    direccion: "Calle Los Jazmines 654, Cajamarca",
    documentoIdentidad: "11223344",
    tipoDocumento: "DNI",
    rol: "tecnico",
  },
  {
    idEmpleado: 10,
    usuario: "patriciadiaz",
    password: "password890",
    nombre: "Patricia",
    apellido: "Díaz",
    correo: "patricia.diaz@example.com",
    telefono: "945872630",
    direccion: "Av. Miraflores 123, Lima",
    documentoIdentidad: "44332211",
    tipoDocumento: "DNI",
    rol: "jefe",
  },
];

export const TIPOS_DE_PRUEBA = [
  {
    idTipoPrueba: 1,
    nombre: "Prueba de resistencia",
    parametros: [
      {
        idParametro: 1,
        nombre: "Fuerza aplicada",
        unidades: "Newton",
      },
      {
        idParametro: 2,
        nombre: "Duración",
        unidades: "Segundos",
      },
    ],
  },
  {
    idTipoPrueba: 2,
    nombre: "Prueba de temperatura",
    parametros: [
      {
        idParametro: 1,
        nombre: "Temperatura inicial",
        unidades: "Celsius",
      },
      {
        idParametro: 2,
        nombre: "Temperatura final",
        unidades: "Celsius",
      },
    ],
  },
  {
    idTipoPrueba: 3,
    nombre: "Prueba de humedad",
    parametros: [
      {
        idParametro: 1,
        nombre: "Humedad relativa",
        unidades: "%",
      },
      {
        idParametro: 2,
        nombre: "Temperatura",
        unidades: "Celsius",
      },
    ],
  },
  {
    idTipoPrueba: 4,
    nombre: "Prueba de voltaje",
    parametros: [
      {
        idParametro: 1,
        nombre: "Voltaje",
        unidades: "Voltios",
      },
      {
        idParametro: 2,
        nombre: "Corriente",
        unidades: "Amperios",
      },
    ],
  },
  {
    idTipoPrueba: 5,
    nombre: "Prueba de presión",
    parametros: [
      {
        idParametro: 1,
        nombre: "Presión inicial",
        unidades: "Pascal",
      },
      {
        idParametro: 2,
        nombre: "Presión final",
        unidades: "Pascal",
      },
    ],
  },
];

export const REPUESTOS = [
  {
    idRepuesto: 1,
    nombre: "Bujía de encendido",
    precio: 15.99,
    descripcion: "Bujía de encendido para motores de combustión interna.",
    linkImg: "https://example.com/bujia.jpg",
    stockActual: 120,
    stockSolicitado: 30,
  },
  {
    idRepuesto: 2,
    nombre: "Filtro de aire",
    precio: 25.5,
    descripcion: "Filtro de aire de alta eficiencia para vehículos.",
    linkImg: "https://example.com/filtro-aire.jpg",
    stockActual: 200,
    stockSolicitado: 50,
  },
  {
    idRepuesto: 3,
    nombre: "Aceite de motor",
    precio: 40.75,
    descripcion: "Aceite sintético para motores de automóviles.",
    linkImg: null,
    stockActual: 150,
    stockSolicitado: 60,
  },
  {
    idRepuesto: 4,
    nombre: "Batería de automóvil",
    precio: 120.0,
    descripcion: "Batería de plomo-ácido de 12V para vehículos automotrices.",
    linkImg: "https://example.com/bateria.jpg",
    stockActual: 80,
    stockSolicitado: 20,
  },
  {
    idRepuesto: 5,
    nombre: "Frenos de disco",
    precio: 85.9,
    descripcion: "Kit de frenos de disco para vehículos de alto rendimiento.",
    linkImg: "https://example.com/frenos-disco.jpg",
    stockActual: 50,
    stockSolicitado: 10,
  },
  {
    idRepuesto: 6,
    nombre: "Amortiguador",
    precio: 45.3,
    descripcion: "Amortiguador para suspensión de vehículos de pasajeros.",
    linkImg: "https://example.com/amortiguador.jpg",
    stockActual: 75,
    stockSolicitado: 25,
  },
  {
    idRepuesto: 7,
    nombre: "Correa de distribución",
    precio: 55.2,
    descripcion: "Correa de distribución de alta resistencia para motores.",
    linkImg: "https://example.com/correa.jpg",
    stockActual: 130,
    stockSolicitado: 40,
  },
];

export const USUARIOS = [
  {
    idUsuario: 1,
    username: "admin",
    password: "admin",
    nombre: "Administrador",
    apellido: "General",
    rol: "admin",
  },
  {
    idUsuario: 2,
    username: "jefe",
    password: "jefe",
    nombre: "Jefe",
    apellido: "de taller",
    rol: "jefe",
  },
  {
    idUsuario: 3,
    username: "supervisor",
    password: "supervisor",
    nombre: "Supervisor",
    apellido: "de pruebas",
    rol: "supervisor",
  },
  {
    idUsuario: 4,
    username: "tecnico",
    password: "tecnico",
    nombre: "Técnico",
    apellido: "de laboratorio",
    rol: "tecnico",
  },
];
